all:
	python3 cv.py 
	python3 explicit_scheme.py 
	python3 linreg.py 
	python3 mainEigenValue.py 
	#Running Neural network
	python3 mainNN.py 20 20 100
	python3 mainNN.py 50 50 100
	python3 mainNN.py 20 20 500  


all-NN:
	python3 cv.py 
	python3 explicit_scheme.py 
	python3 linreg.py 
	python3 mainEigenValue.py 


NN:
	#python3 mainNN.py Nx,Nt, number of iterations
	#Running NN with preset paramaters
	python3 mainNN.py 20 20 100
	python3 mainNN.py 50 50 100
	python3 mainNN.py 20 20 500 



	